<?php
// config/database.php - Auto-generated by installer

define('DB_HOST', 'localhost');
define('DB_NAME', 'smart_order_system');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// Include the main database class
require_once __DIR__ . '/../classes/Database.php';
?>